3.17.0
elastic/apm-agent-nodejs pull request #2140
Opened 2021-07-01 21:51 UTC by astorm

Release (post dated to July 5th, 2022)

2021-07-01 22:10 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2140/detail/PR-2140/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2140/detail/PR-2140/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2140/detail/PR-2140/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2140/detail/PR-2140/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-nodejs_2140.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #2140 opened`



* Start Time: 2021-07-01T21:51:54.109+0000


* Duration: 19 min 37 sec


* Commit: 091087f8898b0e00159a85ff859ad6af3f74bc12



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 19040  |
| Skipped      | 0 |
| Total        | 19040   |


#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2140/buildTimeGraph/png)


![Image of Tests](https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2140/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-07-01 23:54 UTC, astorm commented
jenkins run the tests please

2021-07-02 00:30 UTC, astorm commented
jenkins run the tests please

2021-07-05 21:31 UTC, trentm commented
Test failures above are all spurious AFAICT.

2021-07-05 21:34 UTC, trentm requested changes

2021-07-05 21:34 UTC, trentm commented on CHANGELOG.asciidoc
> +==== 3.17.0 2021/07/5
```suggestion
==== 3.17.0 2021/07/05
```

2021-07-05 21:34 UTC, trentm commented on docs/upgrading.asciidoc
> +|3.17.x |2022-01-05 |3.18.0
```suggestion
|3.17.x |2023-01-05 |3.18.0
```

2021-07-05 21:34 UTC, trentm commented on CHANGELOG.asciidoc
>  ===== Breaking changes
```suggestion
```

2021-07-05 21:34 UTC, trentm commented on CHANGELOG.asciidoc
```suggestion
[[release-notes-3.17.0]]
```

2021-07-05 21:38 UTC, trentm approved these changes

2021-07-05 23:01 UTC, merged

2021-07-05 23:04 UTC, trentm commented
v3.17.0 tagged (https://github.com/elastic/apm-agent-nodejs/releases/tag/v3.17.0) and published (https://www.npmjs.com/package/elastic-apm-node/v/3.17.0)