feat: implement isCompressionEligable method
elastic/apm-agent-nodejs pull request #2656
Opened 2022-04-21 21:04 UTC by astorm

description tk

### Checklist

- [x] Implement code
- [ ] Add tests
- [ ] Update TypeScript typings
- [ ] Update documentation
- [ ] Add CHANGELOG.asciidoc entry
- [ ] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

2022-04-21 23:51 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2656/detail/PR-2656/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2656/detail/PR-2656/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2656/detail/PR-2656/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2656/detail/PR-2656/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-04-21T23:25:22.501Z&rangeTo=2022-04-21T23:45:22.501Z&transactionName=apm-agent-nodejs/apm-agent-nodejs-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=62ee05bfe59fc297e069066f2926855d&transactionId=b5661388c2ead913)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-21T23:35:22.501+0000


* Duration: 16 min 11 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![23](https://img.shields.io/badge/23%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2656/detail/PR-2656/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


> Show only the first 10 steps failures

  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/782/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:13.996Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/780/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:13.792Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/811/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:15.241Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/795/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:14.574Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/829/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:15.895Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/785/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:14.217Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/781/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:13.895Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/799/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:14.727Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/794/log/?start=0">here</a></li>
<li>Description: <code>[2022-04-21T23:51:14.543Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2656/runs/1/steps/699/log/?start=0">here</a></li>
<li>Description: <code>org.jenkinsci.plugins.workflow.steps.FlowInterruptedException</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run module tests for <modules>` : Run TAV tests for one or more modules, where `<modules>` can be either a comma separated list of modules (e.g. memcached,redis) or the string literal ALL to test all modules


- `run benchmark tests` : Run the benchmark test only.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-25 21:40 UTC, trentm requested changes
> Implements: #2604

If you use `Closes`, `Fixes`, or `Resolves` then GitHub will [automatically link this PR to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Unless you intentionally don't want that?


> - HTTP 2 requests will now propagate the the trace context headers

Nice. This is: https://github.com/elastic/apm-agent-nodejs/issues/1830

> - Span compression is enabled by default

This section of "configuration.asciidoc" should be updated for it being on by default now:

```
[[span-compression-enabled]]
==== `spanCompressionEnabled`

...
```

2022-04-26 07:28 UTC, astorm commented on test/instrumentation/span-compression.test.js
> +        `span.composite.sum > ~25: ${span.composite.sum}`)
Not a mis-merge -- perhaps some miscommunication in the  slack this morning.  Sounds like you want these at 30 and that'll be the fastest way to resolution. Done in 163bacfad2699517f8e1e4e6e2ddf001c4235ed4

2022-04-26 15:14 UTC, trentm commented on CHANGELOG.asciidoc
> +* Span compression now obeys the `isCompressionEligable` rules from https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-compress.md#eligibility-for-compression[th
This changelog entry should be merged with the "Adds initial implementation of" item above.

2022-04-26 20:14 UTC, astorm commented on CHANGELOG.asciidoc
> +* Span compression now obeys the `isCompressionEligable` rules from https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-compress.md#eligibility-for-compression[th
Done in 7b0f065590c783672926ce9b0fb4801afbb9d9db

2022-04-26 20:14 UTC, astorm commented on test/instrumentation/span-compression.test.js
> +    t.true(span.isCompressionEligible())
Per offline conversion no action will be taken on this in this PR.

2022-04-26 20:49 UTC, trentm approved these changes

2022-04-27 05:37 UTC, merged