feat: delay loading error-callsites module
elastic/apm-agent-nodejs pull request #2906
Opened 2022-09-04 21:01 UTC by astorm

description tk

### Checklist

- [x] Implement code
- [ ] Add tests
- [ ] Update TypeScript typings
- [ ] Update documentation
- [ ] Add CHANGELOG.asciidoc entry
- [ ] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

2022-09-04 21:16 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2906/detail/PR-2906/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2906/detail/PR-2906/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2906/detail/PR-2906/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2906/detail/PR-2906/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-09-04T20:51:28.394Z&rangeTo=2022-09-04T21:11:28.394Z&transactionName=BUILD+apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=58986d0860821b63ddc39dd9ef26afb1&transactionId=59523f372e5913fb)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-04T21:01:28.394+0000


* Duration: 15 min 46 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![24](https://img.shields.io/badge/24%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp%2FPR-2906/detail/PR-2906/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


> Show only the first 10 steps failures

  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/771/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:57.203Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/803/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:58.453Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/779/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:57.517Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/833/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:59.734Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/804/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:58.474Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/807/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:58.634Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/808/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:58.721Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/832/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-04T21:15:59.702Z] Archiving artifacts
org.jenkinsci.plugins.workflow.steps.FlowInterrupted</code></l1>
</ul>
  
  
  
  
##### `Basic tests I`
<ul>
<li>Took 1 min 36 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/582/log/?start=0">here</a></li>
<li>Description: <code>cd /app && .ci/scripts/test_basic.sh</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/pipelines/PR-2906/runs/1/steps/760/log/?start=0">here</a></li>
<li>Description: <code>org.jenkinsci.plugins.workflow.steps.FlowInterruptedException</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run module tests for <modules>` : Run TAV tests for one or more modules, where `<modules>` can be either a comma separated list of modules (e.g. memcached,redis) or the string literal ALL to test all modules


- `run benchmark tests` : Run the benchmark test only.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-04 21:17 UTC, astorm commented
@trentm still working up a test or two on this one but wanted to run the idea of wrapping `error-callsites` in a lazy load callback and then explicitly loading it in `Agent.start`.  Was this what you had in mind or was there another approach you were considering?

2022-09-06 17:05 UTC, trentm requested changes

2022-09-06 17:43 UTC, trentm commented on test/stacktraces/stacktraces.test.js
> +  tape.test('delayed error-callsite loading', function (t) {
Oh, I missed your comment about tests still being draft: https://github.com/elastic/apm-agent-nodejs/pull/2906#issuecomment-1236417093

2022-09-06 17:44 UTC, trentm commented on lib/agent.js
> +  require('error-callsites')
I think I mostly answered the questions in your comment https://github.com/elastic/apm-agent-nodejs/pull/2906#issuecomment-1236417093 here.

2022-09-06 18:16 UTC, astorm commented on lib/agent.js
> +  require('error-callsites')
Yeah, still writing the tests.  Moving the loading makes sense and an `initStackTraceCollection` function seems like an equally valid way to handle this so I'll do that -- just to say it out loud the trade-off there is `gatherStackTrace` will need a guard that bails early if stack trace collection hasn't been initialized.

2022-09-06 18:29 UTC, trentm commented on lib/agent.js
> +  require('error-callsites')
> just to say it out loud the trade-off there is gatherStackTrace will need a guard that bails early if stack trace collection hasn't been initialized.

Yup, +1.

2022-09-07 21:12 UTC, trentm requested changes
Looks good.

2022-09-07 21:12 UTC, trentm commented on CHANGELOG.asciidoc
> +  `error-callsites` ({issues}2833[#2833] {pull}2906[#2906])
```suggestion
- Agent will delay loading of the `error-callsites` module until agent start time,
  and will not load the module if the agent is disabled/inactive. This prevents the
  setting of an `Error.prepareStackTrace` handler until necessary for stacktrace
  collection. ({issues}2833[#2833] {pull}2906[#2906])
```

2022-09-07 22:26 UTC, trentm approved these changes

2022-09-12 15:09 UTC, merged